import type { NotificationItem } from "./types";

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
	{
		id: "n1",
		type: "proof_uploaded",
		title: "Proof uploaded",
		message: "Sunrise Relief uploaded verified proof for Clean Water Campaign.",
		time: "2m ago",
		unread: true,
	},
	{
		id: "n2",
		type: "donation_successful",
		title: "Donation successful",
		message: "Your donation of $30 to Community Food Drive was successful.",
		time: "15m ago",
		unread: true,
	},
	{
		id: "n3",
		type: "new_creator_post",
		title: "New creator post",
		message: "Mya shared a field update with fresh photos from Shan.",
		time: "1h ago",
		unread: true,
	},
	{
		id: "n4",
		type: "organization_verified",
		title: "Organization verified",
		message: "Helping Hands Org is now verified on DanaLink.",
		time: "3h ago",
		unread: false,
	},
	{
		id: "n5",
		type: "new_campaign_launched",
		title: "New campaign launched",
		message: "Education For All launched School Kits for Monsoon Recovery.",
		time: "5h ago",
		unread: false,
	},
	{
		id: "n6",
		type: "milestone_reached",
		title: "Milestone reached",
		message: "Clean Water Campaign has reached 75% of its funding target.",
		time: "8h ago",
		unread: false,
	},
	{
		id: "n7",
		type: "expense_report_added",
		title: "Expense report added",
		message: "A new expense breakdown is available for Rural Clinic Support.",
		time: "12h ago",
		unread: false,
	},
	{
		id: "n8",
		type: "campaign_completed",
		title: "Campaign completed",
		message: "Blanket Drive Winter 2026 has completed successfully.",
		time: "1d ago",
		unread: false,
	},
	{
		id: "n9",
		type: "creator_milestone",
		title: "Creator milestone",
		message: "Aung reached 100 total campaign updates shared.",
		time: "1d ago",
		unread: false,
	},
	{
		id: "n10",
		type: "thank_you_note",
		title: "Thank you note",
		message: "You received a thank-you note from Hope Together Foundation.",
		time: "2d ago",
		unread: false,
	},
];

